defaults:
  - training: train_diffusion_transformer_real_hybrid_dino_multi_gpu_workspace
  - _self_

_target_: env_runner.real_env_runner.RealEnvRunner
fps: 10

device_ids: '0'
checkpoint_path: /home/yuwenye/projects/human-in-the-loop/diffusion_policy/data/checkpoints/multi_robot_exp/0912_19.36.00_train_diffusion_transformer_hybrid_dino_multi_gpu_multi_robot_exp_three_robots_fold_towel_round3/latest.ckpt
train_dataset_path: /mnt/workspace/DP/multi_robot_exp/0815_expert_fold_towel_three_robots
save_buffer_path: /mnt/workspace/DP/test/0923_test_codebase_single_robot
output_dir: /home/yuwenye/projects/human-in-the-loop/diffusion_policy/outputs/visual/0923_test_single_robot

Ta: 8
random_init: True
seed: 31

# Failure detection configuration
failure_detection:
  _target_: float.float.FLOAT
  max_queue_size: 3
  num_samples: 1
  num_expert_candidates: 50
  ot_percentile: 95
  soft_ot_ratio: 0.2
  update_stats: False
  Ta: ${Ta}
  train_dataset_path: ${train_dataset_path}
  save_buffer_path: ${save_buffer_path}
  output_dir: ${output_dir}
  enable_visualization: True
  To: ${training.n_obs_steps}
  ee_pose_dim: ${training.shape_meta.obs.ee_pose.shape}
  image_shape: ${training.task.image_shape}

policy:
  num_inference_steps: 8
  obs_encoder:
    pretrained_path: null
  
training:
  output_dir: ${output_dir}