defaults:
  - training: train_diffusion_transformer_real_hybrid_dino_multi_gpu_workspace
  - _self_

_target_: env_runner.real_env_runner.RealEnvRunner
fps: 10

device_ids: '0'
checkpoint_path: /path/to/checkpoint
train_dataset_path: /path/to/trained/dataset
save_buffer_path: /path/to/save/rollout/data
output_dir: /path/to/output/visualization

Ta: 8
random_init: True
seed: 31

# Failure detection configuration
failure_detection:
  _target_: float.float.FLOAT
  max_queue_size: 3
  num_samples: 1
  num_expert_candidates: 50
  ot_percentile: 95
  soft_ot_ratio: 0.2
  update_stats: False
  Ta: ${Ta}
  train_dataset_path: ${train_dataset_path}
  save_buffer_path: ${save_buffer_path}
  output_dir: ${output_dir}
  enable_visualization: True
  To: ${training.n_obs_steps}
  ee_pose_dim: ${training.shape_meta.obs.ee_pose.shape}
  image_shape: ${training.task.image_shape}

policy:
  num_inference_steps: 8
  obs_encoder:
    pretrained_path: null
  
training:
  output_dir: ${output_dir}