defaults:
  - training: train_diffusion_transformer_real_hybrid_dino_multi_gpu_workspace
  - _self_

device_ids: '0'
checkpoint_path: /home/yuwenye/projects/human-in-the-loop/diffusion_policy/data/checkpoints/demo/0816_02.09.55_train_diffusion_transformer_hybrid_dino_multi_gpu_0815_final_fold_towel_three_robots_demo_round2_only_human_intv/latest.ckpt
train_dataset_path: /mnt/workspace/DP/demo/0815_final_fold_towel_three_robots_number_1_round1_disable_action_inconsistency
save_buffer_path: /mnt/workspace/DP/multi_robot_exp/0903_fold_towel_three_robots_first_robot_round1
output_dir: /home/yuwenye/projects/human-in-the-loop/diffusion_policy/outputs/visual/0903_fold_towel_single_robot_round1

Ta: 8
random_init: True
seed: 15

# Failure detection configuration
failure_detection:
  _target_: float.float.FLOAT
  max_queue_size: 3
  num_samples: 4
  num_expert_candidates: 50
  ot_percentile: 95
  soft_ot_ratio: 0.2
  update_stats: False
  Ta: ${Ta}
  train_dataset_path: ${train_dataset_path}
  save_buffer_path: ${save_buffer_path}
  output_dir: ${output_dir}
  enable_visualization: True
  To: ${training.n_obs_steps}
  ee_pose_dim: ${training.shape_meta.obs.ee_pose}
  img_shape: ${training.task.image_shape}

# Sirius-related hyperparameters
post_process_action_mode: False
sirius_termination: False

policy:
  num_inference_steps: 8

# Robot configuration
robot_info:
  num_robots: 2
  # for 1 rbt:
  # socket_ip: "127.0.0.1"
  # for 2 rbts:
  socket_ip: "192.168.1.3"
  socket_port: 12345
  robot_name: flexiv
  robot_id: 0
  robot_info_dict:
    "0":
      ip: "192.168.2.100"
    "1":
      ip: "192.168.3.100"

# Camera configuration
camera:
  serial: 
    - "135122075425"
    - "135122070361"
  fps: 10
  img_shape: [3, 224, 224]