device_ids: '0'
checkpoint_path: /home/yuwenye/projects/human-in-the-loop/diffusion_policy/data/checkpoints/mug/0706_11.06.54_train_diffusion_transformer_hybrid_dino_multi_gpu_0627_mug_ours_dagger_round2/latest.ckpt
output_dir: outputs/visual/debug

Ta: 8
num_episode: 20
random_init: True
seed: 6

policy:
  num_inference_steps: 8
