device_ids: '0'
checkpoint_path: /home/yuwenye/projects/human-in-the-loop/diffusion_policy/data/checkpoints/demo/0811_21.05.37_train_diffusion_transformer_hybrid_dino_multi_gpu_0807_fold_towel_two_robots_demo_round2/latest.ckpt
train_dataset_path: /mnt/workspace/DP/demo/0807_fold_towel_two_robots_round1_new
save_buffer_path: /mnt/workspace/DP/demo/0812_fold_towel_two_robots_round2_base
output_dir: diffusion_policy/outputs/visual/0812_fold_towel_two_robots_rollout_round2

Ta: 8
random_init: True
seed: 10

# Failure detection configuration
failure_detection_module: action_inconsistency_ot

# Failure detection hyperparameters
enable_action_inconsistency: True
enable_OT: True
inconsistency_metric: expert
num_samples: 4
num_expert_candidates: 50
action_inconsistency_percentile: 90
ot_percentile: 95
soft_ot_ratio: 0.2
update_stats: True

# Sirius-related hyperparameters
post_process_action_mode: False
sirius_termination: False

policy:
  num_inference_steps: 8
