device_ids: '0'
checkpoint_path: /home/yuwenye/projects/human-in-the-loop/diffusion_policy/data/checkpoints/pour/0627_19.09.36_train_diffusion_transformer_hybrid_dino_multi_gpu_0627_pour_initial/latest.ckpt
train_dataset_path: /mnt/workspace/DP/pour/0627_pour_ours_dagger_round1_2
save_buffer_path: /mnt/workspace/DP/pour/0627_pour_ours_dagger_round1_3
output_dir: diffusion_policy/outputs/visual/0627_pour_rollout_round1

Ta: 8
random_init: True
seed: 0

# Failure detection hyperparameters
inconsistency_metric: expert
num_samples: 4
num_expert_candidates: 50
action_inconsistency_percentile: 90
ot_percentile: 95
soft_ot_ratio: 0.2

# Sirius-related hyperparameters
post_process_action_mode: False

policy:
  num_inference_steps: 8
