device_ids: '0'
checkpoint_path: /home/yuwenye/projects/human-in-the-loop/diffusion_policy/data/checkpoints/mango_in_drawer/0711_13.32.11_train_diffusion_transformer_hybrid_dino_multi_gpu_0710_mango_in_drawer_ours_dagger_round1/latest.ckpt
train_dataset_path: /mnt/workspace/DP/mango_in_drawer/0710_mango_in_drawer_ours_dagger_round2_1
save_buffer_path: /mnt/workspace/DP/mango_in_drawer/0710_mango_in_drawer_ours_dagger_round2_2
output_dir: diffusion_policy/outputs/visual/0710_mango_in_drawer_rollout_round2

Ta: 8
random_init: True
seed: 1

# Failure detection hyperparameters
enable_action_inconsistency: True
inconsistency_metric: expert
num_samples: 4
num_expert_candidates: 50
action_inconsistency_percentile: 90
ot_percentile: 95
soft_ot_ratio: 0.2

# Sirius-related hyperparameters
post_process_action_mode: False

policy:
  num_inference_steps: 8
