device_ids: '0'
checkpoint_path: /home/yuwenye/projects/human-in-the-loop/diffusion_policy/data/checkpoints/mug/0611_13.17.19_train_diffusion_transformer_hybrid_dino_multi_gpu_mug_dagger_new_round2/epoch=0150-train_loss=0.030.ckpt
train_dataset_path: /mnt/workspace/DP/0604_mug_ours_dagger_new_failure_detection_round2_2
save_buffer_path: /mnt/workspace/DP/0617_mug_recap_ours_dagger_new_failure_detection_round3_1
output_dir: diffusion_policy/outputs/visual/0609_mug_rollout_round2

Ta: 8
random_init: True
seed: 5

# Failure detection hyperparameters
inconsistency_metric: expert
num_samples: 32
num_expert_candidates: 50
action_inconsistency_percentile: 90
ot_percentile: 95
soft_ot_ratio: 0.5

# Sirius-related hyperparameters
post_process_action_mode: False

policy:
  num_inference_steps: 8
