device_ids: '0'
checkpoint_path: /home/yuwenye/projects/human-in-the-loop/diffusion_policy/data/checkpoints/mango_in_drawer/0711_10.53.46_train_diffusion_transformer_hybrid_dino_weighted_multi_gpu_0710_mango_in_drawer_sirius_round1/latest.ckpt
train_dataset_path: /mnt/workspace/DP/mango_in_drawer/0710_mango_in_drawer_sirius_round2
save_buffer_path: /mnt/workspace/DP/mango_in_drawer/0710_mango_in_drawer_sirius_round2_1
output_dir: diffusion_policy/outputs/visual/0710_mango_in_drawer_rollout_round2

Ta: 8
random_init: True
seed: 1

policy:
  num_inference_steps: 8
