device_ids: '0'
checkpoint_path: /home/yuwenye/projects/human-in-the-loop/third_party/diffusion_policy/data/checkpoints/0313_14.25.32_train_diffusion_transformer_hybrid_weighted_multi_gpu_pouring_sirius/checkpoints/epoch=0300-train_loss=0.029.ckpt
output_dir: outputs/visual/0313_14.25.32_train_diffusion_transformer_hybrid_weighted_multi_gpu_pouring_sirius

Ta: 15
num_episode: 20
random_init: True
num_action_samples: 10

policy:
  num_inference_steps: 8