device_ids: '0'
checkpoint_path: /home/yuwenye/projects/human-in-the-loop/diffusion_policy/data/checkpoints/fold_towel/0731_12.51.11_train_diffusion_transformer_hybrid_dino_multi_gpu_0728_fold_towel_ours_dagger_round1/latest.ckpt
train_dataset_path: /mnt/workspace/DP/fold_towel/0728_fold_towel
save_buffer_path: /mnt/workspace/DP/fold_towel/0728_fold_towel_round1_FAIL_DETECT
output_dir: diffusion_policy/outputs/visual/0728_fold_towel_rollout_round1

Ta: 8
random_init: True
seed: 0

# Failure detection configuration
failure_detection_module: baseline_logp

# Failure detection hyperparameters
baseline_model_path: /home/yuwenye/projects/human-in-the-loop/diffusion_policy/data/baseline_data/0728_fold_towel_ours_dagger_round1/baseline.pt
baseline_stats_path: /home/yuwenye/projects/human-in-the-loop/diffusion_policy/data/baseline_data/0728_fold_towel_ours_dagger_round1/target_traj.npz
baseline_normalizer_path: /home/yuwenye/projects/human-in-the-loop/diffusion_policy/data/baseline_data/0728_fold_towel_ours_dagger_round1/normalizer.pt
post_process_action_mode: False
sirius_termination: False

policy:
  num_inference_steps: 8