device_ids: '0'
checkpoint_path: /home/yuwenye/projects/human-in-the-loop/diffusion_policy/data/checkpoints/mug/0705_23.48.55_train_diffusion_transformer_hybrid_dino_weighted_multi_gpu_0627_mug_sirius_round2/latest.ckpt
train_dataset_path: /mnt/workspace/DP/mug/0627_mug_sirius_round2
save_buffer_path: /mnt/workspace/DP/mug/0627_mug_sirius_round3_test_code
output_dir: diffusion_policy/outputs/visual/0627_mug_rollout_round3

Ta: 8
random_init: True
seed: 2

# No failure detection for Sirius rollout
# failure_detection_module: null

# Sirius-related hyperparameters  
post_process_action_mode: True
sirius_termination: True

policy:
  num_inference_steps: 8
