name: debug

image_shape: [3, 224, 224]
dataset_path: /home/yuwenye/project/human-in-the-loop/diffusion_policy/data/multi_robot_exp/0912_final_three_robots_fold_towel_only_human_round3

shape_meta: &shape_meta
  # acceptable types: rgb, low_dim
  obs:
    wrist_img:
      shape: ${....image_shape}
      type: rgb
    side_img:
      shape: ${....image_shape}
      type: rgb
    ee_pose:
      shape: [9]
      type: low_dim
      rotation_rep: rotation_6d
  action: 
    shape: [10]
    rotation_rep: rotation_6d

env_runner:
  _target_: diffusion_policy.env_runner.myrunner.MyRunner

dataset:
  _target_: diffusion_policy.dataset.mydataset.MyDataset
  zarr_path: /home/yuwenye/project/human-in-the-loop/diffusion_policy/data/multi_robot_exp/0912_final_three_robots_fold_towel_only_human_round3/replay_buffer.zarr
  horizon: ${...horizon}
  pad_before: ${eval:'${...n_obs_steps}-1'}
  pad_after: ${eval:'${...n_action_steps}-1'}
  seed: 42
  val_ratio: 0.00
  max_train_episodes: 100000
  rel_ee_pose: False
  n_obs_steps: ${...n_obs_steps}
  shape_meta: ${shape_meta}
  random_crop: True
  color_jitter: True
  image_shape: ${..image_shape}
